name: Docker Deployment

# Definir cuándo debe ejecutarse el workflow (cuando haya un push en la rama main)
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del código del repositorio
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Paso 2: Configurar el acceso SSH para el servidor remoto
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Paso 3: Crear un archivo tar del contenido del proyecto
    - name: Archive Project Files
      run: |
        tar -czf project-files.tar.gz .

    # Paso 4: Copiar el archivo tar al servidor remoto
    - name: Copy Files to Remote Server
      run: |
        scp -o StrictHostKeyChecking=no project-files.tar.gz adminpira@pirasoft.co:/var/www/html/

    # Paso 5: Descomprimir y Ejecutar Docker Compose en el servidor remoto
    - name: Deploy Application via SSH
      run: |
        ssh -o StrictHostKeyChecking=no adminpira@pirasoft.co << 'EOF'
        set -e
        cd /var/www/html
        tar -xzf project-files.tar.gz -C /var/www/html/projects
        rm project-files.tar.gz
        cd /var/www/html/projects
        docker-compose down || true
        docker-compose up -d --build
        EOF
